name: Maven JavaCI Workflow

on: 
 workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@4.2.2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
       java-version: '17'
       distribution: 'oracle'
    - run:
        mvn --batch-mode --update-snapshots verify
        mkdir staging && cp target/*.jar staging
    - name: Upload a Build Artifact
      with:
       name: drop
       path: staging
    
        
    
       
   
